spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: auth-service
logging:
  level:
    feign.Logger: DEBUG
    com.chuckcha.tt.authservice.feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG