server:
  port: 8081
spring:
  data:
    redis:
      host: localhost
      port: 6379
      username: auth-service
      password: auth-password
  cloud:
    openfeign:
      discovery:
        enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    org.springframework.security.web: DEBUG

security:
  jwt:
    private-key-path: keys/private.pem
    public-key-path: keys/public.pem
    access-token-expiration: 1
    refresh-token-expiration: 30