application:
  config:
    user-url: http://localhost:8222/api/v1/users
server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: chuckcha
    password: chuckcha
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      username: auth-service
      password: auth-password
  cloud:
    discovery:
      enabled: true

security:
  jwt:
    private-key-path: classpath:keys/private.pem
    public-key-path: classpath:keys/public.pem
    access-token-expiration: 1
    refresh-token-expiration: 30