server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: task-service
          uri: lb:http://TASK-SERVICE
          predicates:
            - Path=/api/v1/tasks/**
        - id: auth-service
          uri: lb:http://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
  data:
    redis:
      host: localhost
      port: 6379
      username: gateway
      password: gateway-password

app:
  auth:
    whitelist:
      - /api/v1/auth/login
      - /api/v1/auth/register

security:
  jwt:
    public-key-path: classpath:keys/public.pem