server:
  port: 8075
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
      group-id: EMAIL_SENDING_TASKS
      trusted-packages: com.chuckcha.tt.core.event
      auto-offset-reset: latest
      isolation-level: read_committed