server:
  port: 8072
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
      acks: all
      delivery-timeout: 10000
      request-timeout: 3000
      linger: 0
      enable-idempotence: true
      max-in-flight-requests: 4
      transaction-id-prefix: scheduler-service-${random.value}-
      topic-name: EMAIL_SENDING_TASKS
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: chuckcha
    password: chuckcha
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true